# GitHub Pages configuration
enforce_ssl: true

# Site configuration
title: "2BPW - 2 Beats Per Week"
description: "Minimal techno radio broadcasting 2 beats per week"
url: "https://2bpw.eu.org"
baseurl: ""

# Security headers
plugins:
  - jekyll-sitemap